### ISSUE TITLE
Duplicate transaction ids

### ISSUE THREAD

**Issue by micspiir** [lunarway/openbanking#16]
When getting transactions we see many cases of duplicate ids on transactions. It is not all transactions that have the same id, but almost, often with hundreds of transactions with the same id. Let me know if you need more information.

**Comment by dentych** [comment]
Hey.

When was the exact timestamp for this request?

**Comment by micspiir** [comment]
This happens all the time actually. I just looked up an example now with 2520 duplicate ids out of 2547 transactions. We sent that request at 2021-11-18 08:39:50.252.

In our last integration towards you we didn't see the problem with the ids. Maybe you could look into what the difference is? Would be perfect if they could stay the same.

**Comment by dentych** [comment]
It looks like we had a bit of pointer/range magic issue, which put the last transaction ID on all the transactions. 

I have deployed a fix to production, so IDs should be correct now. ✅

**Comment by micspiir** [comment]
Unfortunately we still see the problem. Taking an example from this morning, we sent a request at 2021-11-19 06:53:34.113.

We received 1916 transactions, but there were only 20 unique ids.
