### ISSUE TITLE
Root CA not trusted

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#21]
Hi,
when trying to onboard a client, we are getting `400 The SSL certificate error`.

`openssl s_client -connect openbanking.prod.lunar.app:443` shows that you do not trust the root CA, the client has.
Can you add **InfoCert Root CA 3** with serial number ** 7c35de37e34e4917f4a8d9f7c92bcaa4f9ee6afa** to your trusted roots?
http://cert.infocert.it/ca3/root/CA.crt

**Comment by bsnlunar** [comment]
tjek we will look into this

**Comment by hoeg** [comment]
Fix should be out now @mbospiir, let me know if it is not working as intended on your end.

**Comment by mbospiir** [comment]
It's doesn't work, the `openssl s_client -connect openbanking.prod.lunar.app:443` dumps the following (no InfoCert there):
```
Acceptable client certificate CA names
C = DK, O = TRUST2408, CN = TRUST2408 OCES Primary CA
C = NO, O = ZebSign AS-983163432, CN = ZebSign Community ID CA 1
C = NO, O = Buypass AS-983163327, CN = Buypass Class 3 CA 1
C = NO, O = Buypass AS-983163327, CN = Buypass Class 3 CA 3
C = NO, O = Buypass AS-983163327, CN = Buypass Class 3 CA 2
C = NO, organizationIdentifier = NTRNO-983163327, O = Buypass AS, CN = Buypass Class 3 CA G2 QC WA
C = NO, organizationIdentifier = NTRNO-983163327, O = Buypass AS, CN = Buypass Class 3 CA G2 HT Person
C = NO, organizationIdentifier = NTRNO-983163327, O = Buypass AS, CN = Buypass Class 3 CA G2 HT Business
C = NO, organizationIdentifier = NTRNO-983163327, O = Buypass AS, CN = Buypass Class 3 CA G2 ST Business
CN = CPN Person High SHA256 CLASS 3, OU = Commfides Trust Environment (c) 2011 Commfides Norge AS, O = Commfides Norge AS - 988 312 495, C = NO
CN = Commfides CPN Person-High CA, OU = Commfides Trust Environment (C) 2006 Commfides Norge AS, OU = CPN Person-High Certificate Authority, O = Commfides Norge AS - 988 312 495, C = NO
CN = CPN Enterprise SHA256 CLASS 3, OU = Commfides Trust Environment (c) 2011 Commfides Norge AS, O = Commfides Norge AS - 988 312 495, C = NO
C = NO, O = Commfides Norge AS, organizationIdentifier = NTRNO-988312495, CN = Commfides Natural Person - G3
C = NO, O = Commfides Norge AS, organizationIdentifier = NTRNO-988312495, CN = Commfides Legal Person - G3
C = NO, O = Fokus Bank, OU = 977074010, CN = BankID Fokus Bank Bank CA 2
C = NO, O = Fokus Bank ASA, OU = 810969652, CN = BankID Fokus Bank Bank CA 1
C = NO, O = Danske Bank A/S, OU = 977074010, CN = BankID - Danske Bank - Bank CA 3
C = NO, O = Bankenes ID-tjeneste AS, OU = 988477052, CN = BankID Bankenes ID-tjeneste Bank CA 2
C = NO, O = Bankenes ID-tjeneste AS, OU = 988477052, CN = BankID Bankenes ID-tjeneste Bank CA 1
C = NO, O = Bankenes ID-tjeneste AS, OU = 988477052, CN = BankID - Bankenes ID-tjeneste AS - Bank CA 3
C = NO, O = DnB NOR Bank ASA, OU = 984851006, CN = BankID DnB NOR Bank CA 2
C = NO, O = DnB NOR Bank ASA, OU = 984851006, CN = BankID DnB NOR Bank CA 1
C = NO, O = DNB Bank ASA, OU = 984851006, CN = BankID - DNB - Bank CA 3
C = NO, O = Nordea Bank Norge ASA, OU = 911044110, CN = BankID Nordea Bank CA 2
C = NO, O = Nordea Bank Norge ASA, OU = 911044110, CN = BankID Nordea Bank CA 1
C = NO, O = "Nordea Bank Abp, filial i Norge", OU = 920058817, CN = BankID - Nordea - Bank CA 3
C = NO, O = Nordea Bank Abp filial i Norge, OU = 920058817, CN = BankID - Nordea - Bank CA 3
C = NO, O = Terra Gruppen AS, OU = 979319568, CN = BankID Terra Gruppen Bank CA 2
C = NO, O = Terra Gruppen AS, OU = 979319568, CN = BankID Terra Gruppen Bank CA 1
C = NO, O = Eika Gruppen AS, OU = 979319568, CN = BankID - Eika Gruppen AS - Bank CA 3
C = NO, O = Alliansesamarbeidet SpareBank 1 DA, OU = 986401598, CN = BankID SpareBank 1 Bank CA 2
C = NO, O = SpareBank 1 Utvikling DA, OU = 986401598, CN = BankID SpareBank 1 Bank CA 1
C = NO, O = SpareBank 1 Banksamarbeidet DA, OU = 986401598, CN = BankID - SpareBank 1 - Bank CA 3
C = NO, O = SpareBank 1 Utvikling DA, OU = 986401598, CN = BankID - SpareBank 1 - Bank CA 3
C = NO, O = SEB Privatbanken ASA, OU = 982582709, CN = BankID SEB Bank CA 2
C = NO, O = SEB Privatbanken ASA, OU = 982582709, CN = BankID SEB Privatbanken Bank CA 1
C = NO, O = Handelsbanken NUF, OU = 971171324, CN = BankID Handelsbanken Bank CA 2
C = NO, O = Handelsbanken NUF, OU = 971171324, CN = BankID Handelsbanken Bank CA 1
C = NO, O = Skandiabanken AB NUF, OU = 981291220, CN = BankID Skandiabanken Bank CA 2
C = NO, O = SkandiaBanken AB NUF, OU = 981291220, CN = BankID SkandiaBanken Bank CA 1
DC = com, DC = statoil, C = NO, O = Statoil ASA - 923609016, CN = Statoil Root CA
C = NO, O = Signicat AS, CN = signicat-p-tsa
C = SE, O = Signguard Europe AB, OU = QualifiedUserCA2008, CN = Signguard QualifiedUserCA2008
C = SE, O = Signguard Europe AB, OU = Certificate Authority, CN = Signguard OCSP-1:PN, emailAddress = ocsp@signguard.se
C = SE, O = TrustWeaver AB, CN = tseiod.trustweaver.com, serialNumber = 164909464210
C = SE, O = TrustWeaver AB, CN = TrustWeaver Signature Validation Service, serialNumber = VAT: SE556613626201
C = SE, O = TrustWeaver, CN = TrustWeaver CA
C = SE, postalCode = 11156, street = "Box 3437, Stockholm", emailAddress = support@zealid.com, organizationIdentifier = SE5569724288, O = ZealiD AB, CN = ZealiD Issuing CA 2020
```

**Comment by hoeg** [comment]
Looking into this.

**Comment by hoeg** [comment]
@mbospiir hopefully the issue is fixed now. Please give it another try and let me know if you encounter any issues.

**Comment by mbospiir** [comment]
On Thursday, when I opened this issue, we were getting a 400 status code with "The SSL certificate error" info.
On Friday, as well as today, we are getting a 403 with no response body.
So there is an improvement, but why the 403 now? There is no authentication but still, something with a certificate must be off - it is still not listed here... `openssl s_client -connect openbanking.prod.lunar.app:443`

**Comment by hoeg** [comment]
Yes, we have located an error with our certificate parsing that I am looking into. Will update as soon as it has been fixed.

**Comment by hoeg** [comment]
@mbospiir we applied a new fix that should fix this issue.

**Comment by mbospiir** [comment]
I can see that the intermediate certificate is added: `InfoCert Organization Validation SHA256 - CA 3`
But the request still fails with a 403:
```
------- Request -----------
Endpoint: https://openbanking.prod.lunar.app/tpp/register


------- Response -----------
Status: 403
Date: Mon, 03 Jan 2022 09:49:14 GMT
Content-Length: 0
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains; preload
```

**Comment by hoeg** [comment]
Ok, would you mind dropping me your client certificate so I can verify that we have the proper certificate chain available on our end?

**Comment by mbospiir** [comment]
@hoeg sent

**Comment by hoeg** [comment]
@mbospiir We have identified another issue with the registration and are still working on a fix.

**Comment by hoeg** [comment]
We have made some changes to the registration flow internally. Hopefully this will resolve the issues. Let me know if you are able to register or not @mbospiir

**Comment by mbospiir** [comment]
Yes, we were able to register, thank you!
