### ISSUE TITLE
GET /aisp-pisp/accounts/{accountId}/transactions returns - Internal server error

### ISSUE THREAD

**Issue by DTeivens** [lunarway/openbanking#69]
I can get successful request for get account list but on GET /aisp-pisp/accounts/{accountId}/transactions it returns - Internal server error

I have tried to use all 3 account ids but with no luck.
Here is request and response :

psd2_request_debug=GET /aisp-pisp/accounts/18de45f7-764b-43ca-a388-19b9f5820686/transactions?from=2023-11-26&to=2024-02-23 HTTP/1.1
X-Nordigen-Use-Payload-As-Index: true
X-Nordigen-Certificate-Type: EIDAS
Authorization: [MASKED]
X-Request-ID: c47fa806-c793-4bce-9d7a-acaa4a576b1e
Content-Type: application/json

, psd2_response_debug=HTTP/1.1 500 Internal Server Error
Date: Fri, 23 Feb 2024 13:05:42 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Proxygen-Request-Success: true
X-Postigen-Response-URL: https://sandbox.openbanking.prod.lunar.app/aisp-pisp/accounts/18de45f7-764b-43ca-a388-19b9f5820686/transactions?from=2023-11-26&to=2024-02-23

Internal server error.

also tried request without date_from and date_to with the same result

**Comment by dentych** [comment]
Hello. Apologies for the delay in response.

I have just deployed a fix to production, so the sandbox should no longer return an internal server error 👍

**Comment by DTeivens** [comment]
Sadly the issue still persists:
psd2_request_debug=GET /aisp-pisp/accounts/18de45f7-764b-43ca-a388-19b9f5820686/transactions?from=2023-12-03&to=2024-03-01 HTTP/1.1
X-Nordigen-Use-Payload-As-Index: true
X-Nordigen-Certificate-Type: EIDAS
Authorization: [MASKED]
X-Request-ID: 28fe53d5-6c16-40aa-a696-f10e59e215bc
Content-Type: application/json

, psd2_response_debug=HTTP/1.1 500 Internal Server Error
Date: Fri, 01 Mar 2024 13:30:20 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 21
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Proxygen-Request-Success: true
X-Postigen-Response-URL: https://sandbox.openbanking.prod.lunar.app/aisp-pisp/accounts/18de45f7-764b-43ca-a388-19b9f5820686/transactions?from=2023-12-03&to=2024-03-01

Internal server error.

tried without date_to and date_from , still the same result

**Comment by dentych** [comment]
Hey! Apologies for this.

The pod has never been successfully deployed to the sandbox environment. We're currently looking into a fix. It's a configuration issue.

I'll update this ticket again once it's resolved

**Comment by dentych** [comment]
The newest change should now be out in the sandbox, so please try again!

**Comment by DTeivens** [comment]
Thank you for the fix , i was able to get transactions
